### ISSUE TITLE
Some functions are too strict

### ISSUE THREAD

**Issue by sergv** [ivan-m/wl-pprint-text#11]
Some functions in `wl-pprint-text` package force their arguments while corresponding functions in `wl-pprint` do not. This leads to semantics being different between the two libraries, i.e. different output, and different performance characteristics when, for example, rendering documents that do not fit into the memory.

For example, consider the function `beside`, which is used to implement horizontal concatenation `<>` and `mappend`. Needless to say, horizontal concatenation is used very frequently, so this affects just about every usage of `wl-pprint-text`. Most of the time this causes no visible effects, but sometimes it does strike, as this ghci session demonstrates:

```
λ> :set -package wl-pprint-text -package wl-pprint -XOverloadedStrings
λ> import qualified Text.PrettyPrint.Leijen as WLPPrint
λ> import qualified Text.PrettyPrint.Leijen.Text as WLPPrintText
λ> WLPPrint.vcat [WLPPrint.string "foo", WLPPrint.empty, WLPPrint.string "bar"]
foo

bar
λ> WLPPrintText.vcat [WLPPrintText.string "foo", mempty, WLPPrintText.string "bar"]
foo
bar
```

In other words, empty document in `wl-pprint` can serve as empty string of sorts, but that's not the case in `wl-pprint-text`. So, at least in this respect, `wl-pprint-text` is not a drop-in replacement for `wl-pprint`. For the same reason it is not a drop-in replacement for other prettyprinting packages like `ansi-wl-pprint` or `wl-pprint-extras`, as they also don't perform check for empty documents.

In addition to `beside`, following functions also have this problem: `<+>`, `<++>`, `splitWithBreak`, `splitWithLine`, `indent`, `nest`. In effect, this prevents lazy rendering of `Doc`, as forcing documents produced by one of these functions will cause arguments to be forced. This introduces problems when documents are large and do not fit into the memory. There's no inherent need to keep full `Doc` in memory when doing rendering.

Changing strictness of functions I mentioned will change the semantics, which may be undesirable. However, I think it's worth to do it to get compatibility with other prettyprinting libraries and to improve handling of very large documents.

**Comment by ivan-m** [comment]
Well, no `wl-pprint-text` is not a 100% drop-in replacement for `wl-pprint` as I found issues regarding whitespace that `wl-pprint` didn't handle well (and this is documented at the top).

In my opinion, this is the correct behaviour of `vcat`: vertically concatenating documents, and the empty document shouldn't contain its own line because it's _empty_.  The empty document is now an identity for `<+>`, `<$$>`, etc.

Because of this, it does require examining a `Doc` to determine if it's the empty document or not.  This may prevent laziness, but I believe the semantics/behaviour of these functions is more important and as such this will not be changed.

**Comment by Bodigrim** [comment]
> The empty document is now an identity for <+>, <$$>, etc.

Having the same neutral element for different operators raises questions about associativity. Is `"a" <> empty <+> "b"` equal to `"a" <> (empty <+> b)` (which is `ab`) or to `(a <> empty) <+> b` (which is `a b`)?
